# can add as many user-defined stages as desired.
# but .pre and .post had precedence above all else regardless of being explicitly declared/defined or not
# default order: .pre, build, test, deploy, .post
# when: default in on_success
stages: [validate, build, confirm, test, lint, deploy]

prerequisite-job:
  stage: .pre
  script: 
    - python --version
    - where python
    - node --version
    - where node
  environment: dev

validate-job:
  stage: validate
  script: 
    - python sample.py
    - node sample.js
  environment: dev

build-job:
  stage: build
  needs:
    - job: prerequisite-job
    - job: validate-job
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  environment: dev

confirm-BE-job:
  stage: confirm
  script:
    - ping localhost
    - echo "localhost pinged."

confirm-FE-job:
  stage: confirm
  script:
    - ping www.google.com
    - echo "google pinged."

test-BE-job:
  stage: test
  needs:
    - job: confirm-BE-job
    - job: confirm-FE-job
  script:
    - echo "This job tests backend functionalities."
  environment: testing

test-FE-job:
  stage: test
  script:
    - echo "This job tests frontend functionalities."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job-BE."
    - sleep 20
  environment: testing

test-microservices-job:
  stage: test
  needs: [test-job-BE, test-job-FE]
  when: always
  script:
    - echo "This job tests microservices."
  environment: testing

lint-job:
  stage: lint
  when: manual

pre-deploy-job:
  stage: deploy
  script: 
    - echo "Prepare for launch"

deploy-prod-job:
  stage: deploy
  needs: [pre-deploy-job]
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "Toggle off instance runners to bypass account verification."
  environment: production

cleanup-job:
  stage: .post
  when: always
  script:
    - echo "Cleaning up..."
    - sleep 10
    - echo "Done."
